// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=cron_test
//

// Package cron_test is a generated GoMock package.
package cron_test

import (
	context "context"
	reflect "reflect"
	time "time"

	cron "github.com/candacelabs/candacelib/cron"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MockStore) Claim(arg0 context.Context, arg1 cron.ClaimRequest) (cron.ClaimResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", arg0, arg1)
	ret0, _ := ret[0].(cron.ClaimResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockStoreMockRecorder) Claim(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockStore)(nil).Claim), arg0, arg1)
}

// Complete mocks base method.
func (m *MockStore) Complete(arg0 context.Context, arg1 cron.Completion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockStoreMockRecorder) Complete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockStore)(nil).Complete), arg0, arg1)
}

// Expired mocks base method.
func (m *MockStore) Expired(arg0 context.Context, arg1 time.Time, arg2 int) ([]cron.OccurrenceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expired", arg0, arg1, arg2)
	ret0, _ := ret[0].([]cron.OccurrenceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Expired indicates an expected call of Expired.
func (mr *MockStoreMockRecorder) Expired(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expired", reflect.TypeOf((*MockStore)(nil).Expired), arg0, arg1, arg2)
}

// Reconcile mocks base method.
func (m *MockStore) Reconcile(arg0 context.Context, arg1 []cron.JobDefinition, arg2 time.Time) ([]cron.JobState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", arg0, arg1, arg2)
	ret0, _ := ret[0].([]cron.JobState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockStoreMockRecorder) Reconcile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockStore)(nil).Reconcile), arg0, arg1, arg2)
}

// Renew mocks base method.
func (m *MockStore) Renew(arg0 context.Context, arg1 cron.LeaseRenewal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockStoreMockRecorder) Renew(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockStore)(nil).Renew), arg0, arg1)
}

// Skip mocks base method.
func (m *MockStore) Skip(arg0 context.Context, arg1 cron.SkipRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skip", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Skip indicates an expected call of Skip.
func (mr *MockStoreMockRecorder) Skip(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*MockStore)(nil).Skip), arg0, arg1)
}

// Snapshot mocks base method.
func (m *MockStore) Snapshot(arg0 context.Context) (cron.StoreSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", arg0)
	ret0, _ := ret[0].(cron.StoreSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStoreMockRecorder) Snapshot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockStore)(nil).Snapshot), arg0)
}
