// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: boundedbuffer/v1/buffer.proto

package boundedbufferv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candacelib/liquidproto"
)

// ValidateRetention validates Liquid Proto field predicates.
func ValidateRetention(message *Retention) error {
	if message == nil {
		return fmt.Errorf("ValidateRetention: nil *Retention")
	}
	if !(message.MaxBytes > 0 && message.MaxBytes <= 2147483647) {
		return &liquidproto.Error{
			Message:   "candace.boundedbuffer.v1.Retention",
			Field:     "max_bytes",
			Predicate: "this > 0 && this <= 2147483647",
			Value:     message.MaxBytes,
		}
	}
	return nil
}
